spring.application.name=smart-queue-backend

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d6si2a15pdvs73drgq30-a.oregon-postgres.render.com:5432/smartqueue_ncnj
spring.datasource.username=root
spring.datasource.password=ZwiqvGMJIXyQGyIplmocc4bkJ3qRtdRp

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

jwt.secret=smartqueue_super_secret_key_12345
jwt.expiration=86400000